export const extensionPreviewClasses = [
  {
    id: 'class-math',
    name: 'Mathematics',
    icon: 'fa-square-root-variable',
    days: ['Monday', 'Wednesday'],
    teacher: 'Mr. Carter',
    description: 'Algebra practice, weekly problem sets, and concept review for the next exam.',
    room: 'Room A-204',
    schedules: [
      { day: 'monday', time: '08.00 - 09.30' },
      { day: 'wednesday', time: '10.00 - 11.30' },
    ],
    links: [
      { title: 'Formula Sheet', url: 'https://www.khanacademy.org/' },
      { title: 'Practice Questions', url: 'https://www.desmos.com/' },
    ],
  },
  {
    id: 'class-physics',
    name: 'Physics',
    icon: 'fa-atom',
    days: ['Tuesday'],
    teacher: 'Ms. Morgan',
    room: 'Lab B-102',
    time: '13.00 - 14.40',
    links: [{ title: 'Lab Resources', url: 'https://phet.colorado.edu/' }],
  },
  {
    id: 'class-chemistry',
    name: 'Chemistry',
    icon: 'fa-flask',
    days: ['Thursday'],
    teacher: 'Mrs. Hall',
    room: 'Room 301',
    time: '09.00 - 10.40',
  },
  {
    id: 'class-history',
    name: 'History',
    icon: 'fa-landmark',
    days: ['Friday'],
    teacher: 'Mr. Reed',
    room: 'Room 112',
    time: '08.00 - 09.40',
  },
  {
    id: 'class-literature',
    name: 'English Literature',
    icon: 'fa-book-open-reader',
    days: ['Friday'],
    teacher: 'Ms. Foster',
    room: 'Room 215',
    time: '10.00 - 11.40',
  },
  {
    id: 'class-biology',
    name: 'Biology',
    icon: 'fa-dna',
    days: ['Monday'],
    teacher: 'Dr. Evans',
    room: 'Science Wing',
    time: '14.00 - 15.30',
  },
]

export const extensionPreviewTasks = [
  {
    id: 'task-math-worksheet',
    classId: 'class-math',
    title: 'Finish algebra worksheet',
    type: 'exam',
    priority: 'high',
    dueDate: '2026-03-21',
    description: 'Complete the final 12 questions and check each answer against the formula sheet.',
    completed: false,
    links: [{ url: 'https://www.khanacademy.org/' }],
    files: [
      {
        name: 'algebra-review.pdf',
        size: 245000,
        data: 'data:text/plain;charset=utf-8,Algebra%20review%20preview',
      },
    ],
  },
  {
    id: 'task-literature-essay',
    classId: 'class-literature',
    title: 'Submit reading reflection',
    type: 'individual',
    priority: 'medium',
    dueDate: '2026-03-22',
    description: 'Write one short paragraph about the main character arc and key themes.',
    completed: false,
  },
  {
    id: 'task-math-quiz',
    classId: 'class-math',
    title: 'Upload quiz corrections',
    type: 'group',
    priority: 'low',
    dueDate: '2026-03-19',
    completed: true,
  },
  {
    id: 'task-physics-lab',
    classId: 'class-physics',
    title: 'Complete motion lab report',
    type: 'exam',
    priority: 'medium',
    dueDate: '2026-03-24',
    completed: false,
  },
  {
    id: 'task-chemistry-notes',
    classId: 'class-chemistry',
    title: 'Review bonding notes',
    type: 'individual',
    priority: 'high',
    dueDate: '2026-03-20',
    completed: false,
  },
  {
    id: 'task-history-presentation',
    classId: 'class-history',
    title: 'Prepare presentation slides',
    type: 'group',
    priority: 'medium',
    dueDate: '2026-03-26',
    completed: false,
  },
]

export const extensionPreviewClassId = 'class-math'

export const extensionPreviewData = {
  classes: extensionPreviewClasses,
  tasks: extensionPreviewTasks,
}
