export const DOWNLOAD_URL = 'StudyFlow-v1.3.zip'
export const DASHBOARD_URL = 'https://whyith699-netizen.github.io/StudyFlowDasboarduser/'
export const GITHUB_URL = 'https://github.com/whyith699-netizen/StudyFlow'
export const VERSION = '1.3'

export const featureCards = [
  {
    title: 'Smart Dashboard',
    description: 'All your tasks and classes at a glance.',
    image: 'assets/dashboard.png',
    bgColor: 'bg-blue-50/50',
    hoverBgColor: 'group-hover:bg-blue-50/80',
    colSpan: 'md:col-span-2',
    imageClass: 'object-cover object-top',
    isLarge: true,
  },
  {
    title: 'Task Tracking',
    description: 'Never miss a deadline.',
    image: 'assets/tasks.png',
    bgColor: 'bg-purple-50/50',
    hoverBgColor: 'group-hover:bg-purple-50/80',
    delay: '100ms',
    hoverEffect: 'group-hover:scale-105',
    imageClass: 'object-cover',
  },
  {
    title: 'Drag & Drop',
    description: 'Seamlessly organize your classes.',
    image: 'assets/drag-drop.png',
    bgColor: 'bg-green-50/50',
    hoverBgColor: 'group-hover:bg-green-50/80',
    hoverEffect: 'group-hover:rotate-1',
    imageClass: 'object-cover',
  },
  {
    title: 'Account Sync',
    description: 'Keep your data safe across devices.',
    image: 'assets/accountsyn.png',
    bgColor: 'bg-indigo-50/50',
    hoverBgColor: 'group-hover:bg-indigo-50/80',
    delay: '100ms',
    hoverEffect: 'group-hover:scale-105',
    imageClass: 'object-cover',
  },
  {
    title: 'Easy Setup',
    description: 'Get started in seconds.',
    image: 'assets/add-class.png',
    bgColor: 'bg-orange-50/50',
    hoverBgColor: 'group-hover:bg-orange-50/80',
    delay: '200ms',
    hoverEffect: 'group-hover:-rotate-1',
    imageClass: 'object-cover object-left',
  },
]

export const stickyScrollItems = [
  {
    image: 'assets/dashboard.png',
    title: 'Your Hub for Success.',
    description: 'Access everything from a single, beautiful dashboard. View upcoming tests and your daily schedule without the clutter.',
  },
  {
    image: 'assets/tasks.png',
    title: 'Organize Chaos.',
    description: 'Add and edit tasks, set smart reminders, and sync with your calendar. Never let a due date slip through the cracks again.',
  },
  {
    image: 'assets/drag-drop.png',
    title: 'Flexible Planning.',
    description: 'Effortlessly drag and drop items to reschedule. Customize your workflow to fit your unique study style.',
  },
]

export const installSteps = [
  {
    step: 1,
    title: 'Download the Extension',
    description: 'Get the latest version of Study Flow directly from our repository. It comes as a secure ZIP file ready for manual installation.',
    image: 'assets/install1.png',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-100',
    shadowColor: 'rgba(59,130,246,0.15)',
    numberBg: 'bg-blue-100',
    numberText: 'text-blue-600',
    imageClass: 'object-cover',
  },
  {
    step: 2,
    title: 'Unzip the File',
    description: 'Locate the downloaded file and extract it. You should see a folder containing the manifest and source files.',
    image: 'assets/install2.png',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-100',
    shadowColor: 'rgba(147,51,234,0.15)',
    numberBg: 'bg-purple-100',
    numberText: 'text-purple-600',
    imageClass: 'object-cover',
    reversed: true,
  },
  {
    step: 3,
    title: 'Enable Developer Mode',
    description: 'Navigate to chrome://extensions in your browser bar. Toggle the Developer mode switch in the top right corner.',
    image: 'assets/install3.png',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-200',
    shadowColor: 'rgba(71,85,105,0.15)',
    numberBg: 'bg-slate-200',
    numberText: 'text-slate-700',
    imageClass: 'object-cover object-right',
  },
  {
    step: 4,
    title: 'Drag & Drop to Install',
    description: 'Simply drag the extracted folder directly into the extensions window. Alternatively, click "Load unpacked" and select the folder.',
    image: 'assets/install4.png',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-100',
    shadowColor: 'rgba(234,88,12,0.15)',
    numberBg: 'bg-orange-100',
    numberText: 'text-orange-600',
    imageClass: 'object-cover object-left',
    reversed: true,
  },
  {
    step: 5,
    title: "You're All Set!",
    description: 'Study Flow is now active. Pin it to your toolbar and start upgrading your productivity today.',
    image: 'assets/install5.png',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-100',
    shadowColor: 'rgba(22,163,74,0.15)',
    numberBg: 'bg-green-100',
    numberText: 'text-green-600',
    imageClass: 'object-cover',
    imageStyle: { objectPosition: 'center 25%' },
  },
]
